thermal:
    k: 0.6306 W/m/K
    rho: 992 kg/m^3
    c: 4178 J /kg / K
layers:
  - name: Henle's fiber layer
    z0: 0 um
    d: 7 um
    mua: models.schulmeister.mua.HenlesFiberLayer({wavelength})
  # - name: Photoreceptor layer
  #   z0: 7 cm
  #   d: 60 um
  #   mua: 0 1/cm
  - name: Pigmented RPE
    z0: 67 um
    d: 10 um
    mua: models.schulmeister.mua.RPE({wavelength})
  # - name: Nonpigmented RPE
  #   z0: 77 um
  #   d: 4 um
  #   mua:  0 1/cm
  - name: Choiroid
    z0: 81 um
    d: 170 um
    mua: models.schulmeister.mua.Choroid({wavelength})
laser:
  E0: 1 W/cm^2
  D: 408 um
  wavelength: 530 nm


sensor:
  z: 70 um
  r:
    '@batch':
      - 25 um
      - 0 um

simulation:
  use_approximations: True
  temperature_rise:
    method: quad

  output_file: 'output/CW/{c[laser/D]}-{c[sensor/r]}-Tvst-short.txt'
  output_config_file: 'output/CW/{c[laser/D]}-{c[sensor/r]}-CONFIG-short.yml'
  time:
    - dt: 1 us
      max: 1 ms
    - dt: 0.5 ms
      min: 1.5 ms
      max: 2 s
    - dt: 100 ms
      min: 2.1 s
      max: 200 s
